DROP TABLE IF EXISTS owners;
DROP TABLE IF EXISTS dogs;

CREATE TABLE owners(
owners_id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR (250) NOT NULL
);

CREATE TABLE dogs(
dog_id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(250) NOT NULL,
age INT NOT NULL,
owner_id INT NOT NULL,
FOREIGN KEY (owner_id) REFERENCES owners(owners_id)
);

